version: "3.8"

services:
  angular-tutorial-heros:
    tty: true
    init: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3030:4200'
    volumes:
      - ./:/app:cached
      - app_node_modules:/app/node_modules

    environment:
      - TZ=Asia/Tokyo
      # Angular ng build の確認メッセージスキップ
      - NG_CLI_ANALYTICS=false
      - NODE_ENV=development
      - TINI_SUBREAPER=true
      - NODE_OPTIONS=--max-old-space-size=8192

volumes:
  app_node_modules:
